# Generated by Django 4.0.2 on 2022-02-09 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bil2_file2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file2',
            name='bil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.bil2'),
        ),
    ]
