# Generated by Django 4.0.2 on 2022-02-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_bil_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bil',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
