# Generated by Django 4.0.2 on 2022-02-09 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_bil_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='name',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='bil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.bil'),
        ),
    ]
