# Generated by Django 4.0.2 on 2022-02-09 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_bill_name_alter_file_bil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
    ]
