# Generated by Django 4.0.2 on 2022-02-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.TextField(null=True),
        ),
    ]
