# Generated by Django 4.0.2 on 2022-02-17 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_bil_ip_alter_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file2',
            name='bil',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='bill',
        ),
        migrations.DeleteModel(
            name='Bil2',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='File2',
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
