# Generated by Django 4.0.2 on 2022-02-18 07:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_car_rename_file_filee'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('12635387-0246-4a75-9ebc-7f749226ef14'), unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.IntegerField(choices=[(1, 'Sedan'), (2, 'Truck'), (3, 'SUV')]),
        ),
    ]
