# Generated by Django 4.0.2 on 2022-02-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_car_uuid_alter_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
