# Generated by Django 4.0.2 on 2022-02-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_car_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='uuid',
        ),
    ]
