# Generated by Django 4.0.2 on 2022-02-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_car_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitHis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
